name: Docker Build CI

on:
  push:
    branches: [ "master" ]
  release:
    types: [ published ]

jobs:
  build_and_push_debian_docker:
    name: Build Debian Image (hub.docker)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set sha_short
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "date_info=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./
          file: ./debian/bookworm/Dockerfile
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:debian
            ${{ github.repository }}:debian-${{ steps.vars.outputs.date_info }}
            ${{ github.repository }}:debian-bookworm
            ${{ github.repository }}:debian-bookworm-${{ steps.vars.outputs.date_info }}
  
  build_and_push_debian_github:
    name: Build Debian Image (ghcr)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set sha_short
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "date_info=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./
          file: ./debian/bookworm/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:debian
            ghcr.io/${{ github.repository }}:debian-${{ steps.vars.outputs.date_info }}
            ghcr.io/${{ github.repository }}:debian-bookworm
            ghcr.io/${{ github.repository }}:debian-bookworm-${{ steps.vars.outputs.date_info }}
